"""add route_payload to route_group

Revision ID: 2803e774c676
Revises: 4b8f4570b7d1
Create Date: 2026-04-15 15:24:39.406359

"""
from alembic import op
import sqlalchemy as sa


revision = '2803e774c676'
down_revision = '4b8f4570b7d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('route_group', sa.Column('route_payload', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('route_group', 'route_payload')
    # ### end Alembic commands ###
