"""initial delivery execution schema

Revision ID: cac9c4e16db1
Revises: 
Create Date: 2026-04-01 14:12:47.500125

"""
from alembic import op
import sqlalchemy as sa


revision = 'cac9c4e16db1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('delivery_request',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('order_id', sa.BigInteger(), nullable=False),
    sa.Column('customer_id', sa.BigInteger(), nullable=False),
    sa.Column('request_timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('request_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_delivery_request_customer_id'), 'delivery_request', ['customer_id'], unique=False)
    op.create_index(op.f('ix_delivery_request_order_id'), 'delivery_request', ['order_id'], unique=False)
    op.create_table('route_group',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('scheduled_date', sa.DateTime(timezone=True), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('zone_code', sa.String(), nullable=False),
    sa.Column('total_stops', sa.Integer(), nullable=False),
    sa.Column('estimated_distance_km', sa.DECIMAL(precision=10, scale=2), nullable=True),
    sa.Column('estimated_duration_min', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('customer_details',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('customer_name', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('street', sa.String(), nullable=False),
    sa.Column('city', sa.String(), nullable=False),
    sa.Column('province', sa.String(), nullable=False),
    sa.Column('postal_code', sa.String(), nullable=False),
    sa.Column('country', sa.String(), nullable=False),
    sa.Column('latitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('longitude', sa.DECIMAL(precision=10, scale=7), nullable=True),
    sa.Column('geocode_status', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_request_id')
    )
    op.create_table('customer_details_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('customer_payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_request_id')
    )
    op.create_table('delivery_execution',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('current_status', sa.String(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('dispatched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('out_for_delivery_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_request_id')
    )
    op.create_table('delivery_item',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('external_item_id', sa.BigInteger(), nullable=False),
    sa.Column('item_name', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_request_snapshot',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('delivery_request_id')
    )
    op.create_table('driver_assignment',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_group_id', sa.UUID(), nullable=False),
    sa.Column('driver_id', sa.BigInteger(), nullable=False),
    sa.Column('assignment_status', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reassignment_reason', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('route_stop',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('route_group_id', sa.UUID(), nullable=False),
    sa.Column('delivery_request_id', sa.UUID(), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('estimated_arrival', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stop_status', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_request_id'], ['delivery_request.id'], ),
    sa.ForeignKeyConstraint(['route_group_id'], ['route_group.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_attempt',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_execution_id', sa.UUID(), nullable=False),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('attempted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('outcome', sa.String(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_execution_id'], ['delivery_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_confirmation',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_execution_id', sa.UUID(), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('received_by', sa.String(), nullable=False),
    sa.Column('proof_of_delivery_url', sa.Text(), nullable=True),
    sa.Column('signature_data', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_execution_id'], ['delivery_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('delivery_exception',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_execution_id', sa.UUID(), nullable=False),
    sa.Column('exception_type', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('retry_allowed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['delivery_execution_id'], ['delivery_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pickup_record',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_execution_id', sa.UUID(), nullable=False),
    sa.Column('picked_up_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('location', sa.String(), nullable=True),
    sa.Column('collected_by', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_execution_id'], ['delivery_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('status_history',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_execution_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(), nullable=True),
    sa.Column('new_status', sa.String(), nullable=False),
    sa.Column('changed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('changed_by', sa.String(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['delivery_execution_id'], ['delivery_execution.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('status_history')
    op.drop_table('pickup_record')
    op.drop_table('delivery_exception')
    op.drop_table('delivery_confirmation')
    op.drop_table('delivery_attempt')
    op.drop_table('route_stop')
    op.drop_table('driver_assignment')
    op.drop_table('delivery_request_snapshot')
    op.drop_table('delivery_item')
    op.drop_table('delivery_execution')
    op.drop_table('customer_details_snapshot')
    op.drop_table('customer_details')
    op.drop_table('route_group')
    op.drop_index(op.f('ix_delivery_request_order_id'), table_name='delivery_request')
    op.drop_index(op.f('ix_delivery_request_customer_id'), table_name='delivery_request')
    op.drop_table('delivery_request')
    # ### end Alembic commands ###