"use client"
import { useCallback, useEffect, useState } from "react"
import { getDeliveryRecord, getDriverSchedule, getTracking, type DeliveryRecord, type DeliveryTracking, type DriverSchedule, type DriverSummary } from "@/lib/api-client"
import type { DeliveryStatus } from "@/lib/delivery-status"
export interface PortalStop { routeStopId: string; routeGroupId: string; deliveryRequestId: string; orderId: number; sequence: number; stopStatus: string; estimatedArrival: string | null; address: string; customerName: string; phoneNumber: string | null; deliveryType: string; itemSummary: string; requestStatus: string | null; deliveryStatus: DeliveryStatus; deliveryExecutionId: string | null; assignmentStatus: string | null; routeGroupStatus: string | null; tracking: DeliveryTracking | null; deliveryRecord: DeliveryRecord | null }
export interface PortalData { driver: DriverSummary; schedule: DriverSchedule; stops: PortalStop[] }
const deriveDeliveryStatus = (stopStatus: string, tracking: DeliveryTracking | null): DeliveryStatus => tracking?.delivery_status ?? (stopStatus === 'completed' ? 'delivered' : 'scheduled')
const deriveDeliveryType = (deliveryRecord: DeliveryRecord | null) => { const c = deliveryRecord?.items?.length ?? 0; return c > 0 ? `${c} item${c === 1 ? '' : 's'}` : 'Delivery' }
const deriveItemSummary = (deliveryRecord: DeliveryRecord | null) => { if (!deliveryRecord || deliveryRecord.items.length === 0) return 'No item details available yet'; const names = deliveryRecord.items.slice(0,2).map((i)=>`${i.item_name} (${i.quantity})`); const remaining = deliveryRecord.items.length - names.length; return remaining > 0 ? `${names.join(', ')} +${remaining} more` : names.join(', ') }
async function loadStopDetails(schedule: DriverSchedule): Promise<PortalStop[]> { const stops = await Promise.all(schedule.stops.map(async (stop) => { const [deliveryRecord, tracking] = await Promise.all([getDeliveryRecord(stop.delivery_request_id).catch(() => null), getTracking(stop.order_id).catch(() => null)]); const details = deliveryRecord?.customer_details; const address = details ? [details.street, details.city, details.province, details.postal_code, details.country].filter(Boolean).join(', ') : stop.address || `Order #${stop.order_id}`; return { routeStopId: stop.route_stop_id, routeGroupId: stop.route_group_id, deliveryRequestId: stop.delivery_request_id, orderId: stop.order_id, sequence: stop.sequence, stopStatus: stop.stop_status, estimatedArrival: stop.estimated_arrival, address, customerName: details?.customer_name || `Order #${stop.order_id}`, phoneNumber: details?.phone_number || null, deliveryType: deriveDeliveryType(deliveryRecord), itemSummary: deriveItemSummary(deliveryRecord), requestStatus: deliveryRecord?.request_status ?? null, deliveryStatus: deriveDeliveryStatus(stop.stop_status, tracking), deliveryExecutionId: tracking?.delivery_execution_id ?? null, assignmentStatus: tracking?.assignment_status ?? null, routeGroupStatus: tracking?.route_group_status ?? null, tracking, deliveryRecord } satisfies PortalStop })); return stops.sort((a,b)=>a.sequence-b.sequence) }
export function useDriverPortalData(driver: DriverSummary | null, routeGroupId?: string | null) { const [data, setData] = useState<PortalData | null>(null); const [isLoading, setIsLoading] = useState(false); const [error, setError] = useState<string | null>(null); const refresh = useCallback(async () => { if (!driver || !routeGroupId) { setData(null); setError(null); return } setIsLoading(true); setError(null); try { const schedule = await getDriverSchedule(driver.driver_id, routeGroupId); const stops = await loadStopDetails(schedule); setData({ driver, schedule, stops }) } catch (e) { setError(e instanceof Error ? e.message : 'Unable to load driver route data.'); setData(null) } finally { setIsLoading(false) } }, [driver, routeGroupId]); useEffect(() => { void refresh() }, [refresh]); return { data, isLoading, error, refresh } }
